# Generated by Django 4.0.4 on 2022-05-27 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchadmin',
            name='username',
            field=models.TextField(default='User345'),
        ),
    ]
