# Generated by Django 4.0.4 on 2022-05-27 05:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0006_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('username', models.TextField(default='User345')),
                ('password', models.TextField()),
                ('location', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('zonal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.zonaladmin')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('password', models.TextField()),
                ('father_name', models.TextField()),
                ('dob', models.DateField()),
                ('address', models.TextField()),
                ('money2pay', models.IntegerField()),
                ('money_paid', models.IntegerField()),
                ('no_due', models.BooleanField(default=True)),
                ('student_id', models.IntegerField()),
                ('branch_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.branchadmin')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
