# Generated by Django 4.0.4 on 2022-05-30 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_student_password_alter_student_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='notice_video/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='notice_image/')),
                ('by_admin', models.BooleanField()),
                ('by_branch', models.BooleanField()),
            ],
        ),
    ]
