# Generated by Django 4.0.4 on 2022-05-31 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_notice_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('bag', models.IntegerField()),
                ('uniform', models.IntegerField()),
                ('pen', models.IntegerField()),
                ('id_card', models.IntegerField()),
            ],
        ),
    ]
