# Generated by Django 4.0.4 on 2022-06-01 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_course_registration_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='money2pay',
        ),
        migrations.RemoveField(
            model_name='student',
            name='no_due',
        ),
        migrations.AddField(
            model_name='student',
            name='balance',
            field=models.IntegerField(default=0),
        ),
    ]
