# Generated by Django 4.0.1 on 2022-06-07 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_prf'),
    ]

    operations = [
        migrations.CreateModel(
            name='CRF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.TextField()),
                ('father_name', models.TextField()),
                ('student_id', models.IntegerField()),
                ('payment_done', models.BooleanField(default=True)),
                ('date_of_addmission', models.DateField()),
                ('date_of_completion', models.DateField()),
                ('course_completed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course')),
            ],
        ),
    ]
