# Generated by Django 4.0.1 on 2022-06-07 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_crf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crf',
            old_name='date_of_addmission',
            new_name='date_of_admission',
        ),
    ]
